export const KEEP_NET_IPS = ["149.72.161.59", "149.72.42.201", "149.72.154.87"] as const

export const KEEP_NET_DOMAINS = [
  "signin-authzone.com",
  "verifycloudaccess.com",
  "akibadem.org",
  "isdestek.org",
  "gartnerpeer.com",
  "global-cloud-llc.com",
  "cloudverification.online",
  "accountaccesses.com",
  "shoppingcenter.site",
  "hesapdogrulama.info",
  "banksecure.info",
  "meetingonline-us.com",
  "digitalsecurelogin.co",
  "secureloginshop.net",
  "encryptedconnections.info",
  "trendyoll.club",
  "kurumsalgiris.com",
  "yoursecuregateway.com",
  "securemygateway.com",
  "hadisendekatil.com",
  "updatemyinformation.com",
  "secure-passchanges.com",
  "swift-intel.com",
  "hepsibureda.com",
  "securely-logout.com",
  "sigortacilarbirligi.com",
  "btyardimmasasi.com",
  "sirketiciduyuru.com",
  "bilgilerimiguncelle.com",
  "securelogout.com",
  "securelinked-in.com",
  "theconnectionsuccess.com",
  "sigortacilikhizmetleri.me",
  "securebankingservices.net",
  "guvenlibankacilik.com",
  "insurance-services.me",
  "btservisleri.com",
  "secureloginonline.net",
  "insan-kaynaklari.me",
  "getaccess.store",
] as const

